import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'

import Landing from '../components/Landing'
import Layout from '../components/layout/layout'
import Products from '../components/Products'
import Purchase from '../components/Purchase'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Advantus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />
      <About />
      <Products />
      <Purchase />
      <Contact />
      

    </Layout>
  )
}
